Fix whitespaces errors

diff --git a/rootfs/opt/bin/scw-signal-state b/rootfs/opt/bin/scw-signal-state
--- a/rootfs/opt/bin/scw-signal-state
+++ b/rootfs/opt/bin/scw-signal-state
@@ -9,8 +9,8 @@ curl -s --fail -XPATCH -H "Content-Type: application/json" "$SERVER"/state \
      -d "{\"state_detail\": \"$STATE\"}" -o /dev/null
 
 if [ $? -eq 0 ]; then
-  echo "$STATE signal sent!"
+    echo "$STATE signal sent!"
 else
-  echo "Can't send $STATE signal"
-  exit 1
+    echo "Can't send $STATE signal"
+    exit 1
 fi
diff --git a/rootfs/opt/bin/scw-userdata b/rootfs/opt/bin/scw-userdata
--- a/rootfs/opt/bin/scw-userdata
+++ b/rootfs/opt/bin/scw-userdata
@@ -14,9 +14,9 @@ get() {
         RESPONSE=$(curl --local-port 1-1024 --noproxy '*' --silent --write-out "\n%{http_CODE}\n" $URL)
         CODE=$(echo "$RESPONSE" | sed -n '$p')
         BODY=$(echo "$RESPONSE" | sed '$d')
-	echo "$BODY"
+        echo "$BODY"
     else
-	echo "'curl' dependency is missing." >&2
+        echo "'curl' dependency is missing." >&2
     fi
 }
 
@@ -27,7 +27,7 @@ patch() {
         # Using curl
         RESPONSE=$(curl --local-port 1-1024 --noproxy '*' -X PATCH -d "$DATA" -H "Content-Type: text/plain" --silent --write-out "\n%{http_CODE}\n" $URL)
     else
-	echo "'curl' dependency is missing." >&2
+        echo "'curl' dependency is missing." >&2
     fi
 }
 
